language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: LJR94JXxV6U7orzUO5qnt8xleFvJfRFvKNHMo92HuJ+V6ipJoK61/YXKHHRsBICNd4ZAOPuvMExDTQuEQmcCpkqnnTZ3CbQ/fB+HMuY66tNkubHqtejnhMzV7U3IPPxDXrulMDlzvol/VeRgJS+ojYhE9R7x9BNbwjd5fqWbGG1xC9u2cQcflc0lYIdFGIz2wKZcIvaBeBuArIz1Bluib9fyrtBtr34Os2saJJE4rru4910UWetduGKyvJxhCJ45/Admbe7wW51FYByb2jUed3/JRVO9SSk3DjaGyT8B4+XFxrpO3woUCElH2YFmMJpDrHjZSZo52Mca7CSFXeouu36uZM3qvrUmsQs6mmlcARPow4jbi2ScrkmK76Ahpno0QvXQ4Ebw/hW8BRRnpB3q8rHtvUzEfjzzKZN0wBe+CQw67ek4yvfYlWjrt8VB2kzQcmMo9kCa0ms71BYdij5TbjOAB252IkhIrgNjjjf4ZiSAr371lXHffkKdEzDW6dCLFfsaDJ0t3SsFyiLzgYZsSvuokCwZ32B0FBGhnXPAKgHdvIQWArELKkBrEi+1yM+91q28VSD16E/uad062g8bUT4sgSr4tgIskkdxNnufXy6mZA+dum7G87CxOYRQ8ASsMGKZoGNu09xsbsEJsnYd6mVr1iezTliwvNG/kWLCIts=
    app: limitless-eyrie-11326
